version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      # These variables are read by the Go application
      PORT: ${PORT:-8080}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db # Service name for the database within the Docker network
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    networks:
      - dragonball_network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" # Expose DB port for local access if needed
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dragonball_network

volumes:
  db_data:

networks:
  dragonball_network:
    driver: bridge